//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdPlanGanttTest5.Code {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProdPlanGanttTest5.Code.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT WOR1.&quot;VisOrder&quot;, WOR1.&quot;LineNum&quot;, WOR1.&quot;DocEntry&quot;, WOR1.&quot;ItemCode&quot; AS &quot;Resource&quot;, WOR1.&quot;StartDate&quot;, WOR1.&quot;EndDate&quot;, WOR1.&quot;StageId&quot;, WOR1.&quot;PlannedQty&quot;
        ///, WOR1.&quot;IssuedQty&quot;, ORSC.&quot;ResName&quot;, COALESCE(WOR1.&quot;U_OpSeqNo&quot;,0) AS &quot;OperationSequenceNumber&quot;
        ///, WOR1.&quot;AdditQty&quot; AS &quot;AdditionalQty&quot;
        ///	FROM WOR1
        ///INNER JOIN ORSC ON WOR1.&quot;ItemCode&quot; = ORSC.&quot;ResCode&quot;
        ///	WHERE WOR1.&quot;DocEntry&quot; IN ({0})
        ///	AND WOR1.&quot;ItemType&quot; = 290.
        /// </summary>
        internal static string GetProductionOrderResourceLines {
            get {
                return ResourceManager.GetString("GetProductionOrderResourceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT OWOR.&quot;DocNum&quot;, OWOR.&quot;DocEntry&quot;, OWOR.&quot;CardCode&quot;, OWOR.&quot;OriginNum&quot;
        ///, OWOR.&quot;StartDate&quot;, OWOR.&quot;DueDate&quot;, OWOR.&quot;PlannedQty&quot;, OWOR.&quot;CmpltQty&quot;
        ///	FROM OWOR
        ///	WHERE OWOR.&quot;Status&quot; IN (&apos;P&apos;,&apos;R&apos;)
        ///	AND OWOR.&quot;OriginType&quot; = &apos;S&apos;
        ///	AND OWOR.&quot;OriginNum&quot; IN ({0}).
        /// </summary>
        internal static string GetProductionOrders {
            get {
                return ResourceManager.GetString("GetProductionOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT OWOR.&quot;DocNum&quot;, OWOR.&quot;DocEntry&quot;, OWOR.&quot;CardCode&quot;, OWOR.&quot;OriginNum&quot;
        ///, OWOR.&quot;StartDate&quot;, OWOR.&quot;DueDate&quot;, OWOR.&quot;PlannedQty&quot;, OWOR.&quot;CmpltQty&quot;
        ///	FROM OWOR
        ///	WHERE OWOR.&quot;Status&quot; IN (&apos;P&apos;,&apos;R&apos;)
        ///	AND OWOR.&quot;OriginType&quot; = &apos;S&apos;.
        /// </summary>
        internal static string GetProjects {
            get {
                return ResourceManager.GetString("GetProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select ORCJ.&quot;ResCode&quot;, ORCJ.&quot;WhsCode&quot;, ORCJ.&quot;CapDate&quot;, ORCJ.&quot;SngRunCap&quot; from ORCJ where &quot;CapType&quot; = &apos;I&apos; and ORCJ.&quot;CapDate&quot; &gt;= @startdate and ORCJ.&quot;CapDate&quot; &lt;= @enddate ORDER BY ORCJ.&quot;CapDate&quot;.
        /// </summary>
        internal static string GetResourceCapacities {
            get {
                return ResourceManager.GetString("GetResourceCapacities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ORSB.&quot;ResGrpCod&quot;, ORSB.&quot;ResGrpNam&quot; as &quot;ResName&quot; FROM ORSB.
        /// </summary>
        internal static string GetResourceGroups {
            get {
                return ResourceManager.GetString("GetResourceGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ORSC.&quot;ResCode&quot;, RSC6.&quot;WeekDay&quot;, RSC6.&quot;SngRunCap&quot; FROM ORSC LEFT JOIN RSC6 ON ORSC.&quot;ResCode&quot; = RSC6.&quot;ResCode&quot;.
        /// </summary>
        internal static string GetResourcePlanDatas {
            get {
                return ResourceManager.GetString("GetResourcePlanDatas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ORSC.&quot;ResCode&quot;, ORSC.&quot;ResName&quot;, ORSC.&quot;ResType&quot;, ORSC.&quot;ResGrpCod&quot; FROM ORSC.
        /// </summary>
        internal static string GetResources {
            get {
                return ResourceManager.GetString("GetResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT WOR4.&quot;DocEntry&quot; AS &quot;ProdOrderDocEntry&quot;, WOR4.&quot;StageId&quot;, WOR4.&quot;SeqNum&quot;, WOR4.&quot;StgEntry&quot;, WOR4.&quot;Name&quot;, WOR4.&quot;StartDate&quot;, WOR4.&quot;EndDate&quot;, WOR4.&quot;Status&quot;
        ///	FROM WOR4 
        ///	WHERE WOR4.&quot;DocEntry&quot; IN ({0}).
        /// </summary>
        internal static string GetRouteStages {
            get {
                return ResourceManager.GetString("GetRouteStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ORDR.&quot;DocNum&quot;, ORDR.&quot;DocEntry&quot;, ORDR.&quot;CardCode&quot;, ORDR.&quot;CardName&quot;, ORDR.&quot;DocDueDate&quot;
        ///	FROM OWOR
        ///	INNER JOIN WOR1 ON OWOR.&quot;DocEntry&quot; = WOR1.&quot;DocEntry&quot; AND WOR1.&quot;ItemType&quot; = 290
        ///	INNER JOIN ORDR ON OWOR.&quot;OriginNum&quot; = ORDR.&quot;DocNum&quot;
        ///	WHERE OWOR.&quot;Status&quot; IN (&apos;P&apos;,&apos;R&apos;)
        ///	AND OWOR.&quot;OriginType&quot; = &apos;S&apos;
        ///	GROUP BY ORDR.&quot;DocNum&quot;, ORDR.&quot;DocEntry&quot;, ORDR.&quot;CardCode&quot;, ORDR.&quot;CardName&quot;, ORDR.&quot;DocDueDate&quot;
        ///ORDER BY ORDR.&quot;DocDueDate&quot; ASC.
        /// </summary>
        internal static string GetSalesOrders {
            get {
                return ResourceManager.GetString("GetSalesOrders", resourceCulture);
            }
        }
    }
}
